# Generated by Django 4.2.4 on 2023-09-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutussection',
            name='image_position',
            field=models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], default='LEFT'),
        ),
    ]
