# Generated by Django 4.2.4 on 2023-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentsinglepage',
            name='caption',
            field=models.CharField(default='', max_length=400),
        ),
    ]
