# Generated by Django 4.2.4 on 2023-08-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_first_block_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='first_block_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_block_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_block_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_block_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='first_block_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
