# Generated by Django 4.2.4 on 2023-09-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepagecharacterscarousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='second_block_title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video_block_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='homepagecharacterscarousel',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
