# Generated by Django 4.2.4 on 2023-08-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newssinglepage_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newssinglepage',
            name='body',
        ),
    ]
