# Generated by Django 4.2.4 on 2023-09-03 15:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newssinglepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssinglepage',
            name='body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock(blank=True, null=True)), ('h2', wagtail.blocks.CharBlock(blank=True, null=True)), ('paragraph', wagtail.blocks.CharBlock(blank=True, null=True)), ('image', wagtail.images.blocks.ImageChooserBlock())], use_json_field=True),
        ),
    ]
