# Generated by Django 4.2.4 on 2023-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newssinglepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssinglepage',
            name='caption',
            field=models.CharField(blank=True, null=True),
        ),
    ]
